AWS_ACCESS_KEY_ID     = "AKIAZVJC76RNNUZX6WTY"
AWS_SECRET_ACCESS_KEY = "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"
tfe_organization      = "the-org-name-you-created"
tfe_email             = "200072256@stu.vtc.edu.hk"
region                = "us-east-1"
